### ISSUE TITLE
Error with overlap

### ISSUE THREAD

**Issue by jhjin** [clementfarabet/lua---imgraph#1]
After update, loading imgraph fails with the following error:

t7> require 'imgraph'
error loading module 'libimgraph' from file '/home/min/a/jin81/local/lib/torch/libimgraph.so':
    /home/min/a/jin81/local/lib/torch/libimgraph.so: undefined symbol: Overlap
stack traceback:
    [C]: ?
    [C]: in function 'require'
    ...e/min/a/jin81/local/share/torch/lua/imgraph/init.lua:45: in main chunk
    [C]: in function 'require'
    stdin:1: in main chunk
    [C]: ?

**Comment by clementfarabet** [comment]
This has been fixed.
